server:
  port: 8002

spring:
#  security:
#    user:
#      name: admin
#      password: 123456
  application:
    name: eureka-server
  cloud:
    config:
      enabled: false
# *************************************************************************************************************

eureka:
  instance:
    hostname: 192.168.1.109
    prefer-ip-address: true
  client:
    registerWithEureka: false #是否将自身注册
    fetchRegistry: false #如果为true，启动时报警.
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    eviction-interval-timer-in-ms: 4000 # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    enable-self-preservation: false   # 关闭自我保护模式（缺省为打开）
    renewal-percent-threshold: 0.9   #server期望在每分钟中收到的心跳次数百分比

# *************************************************************************************************************

management:
  endpoints:
    web:
      exposure:
        include: '*'